// src/utils/propertyHelpers.js

// 🏘 Property Categories with full range
export const propertyCategories = {
  Apartment: [
    "1 Room",
    "2 Rooms",
    "3 Rooms",
    "Self Contain",
    "Mini Flat", 
    "1 Bedroom Flat",
    "2 Bedroom Flat",
    "3 Bedroom Flat",
    "4 Bedroom Flat",
    "5 Bedroom Flat",
    "Penthouse Apartment",
    "Luxury Apartment",
  ],

  Duplex: [
    "2 Bedroom Duplex",
    "3 Bedroom Duplex",
    "4 Bedroom Duplex",
    "5 Bedroom Duplex",
    "6 Bedroom Duplex",
    "7 Bedroom Duplex",
    "Luxury Duplex",
  ],

  Land: [
    "Quarter Plot",
    "Half Plot",
    "1 Plot",
    "2 Plots",
    "3 Plots",
    "5 Plots",
    "10 Plots",
    "20 Plots",
    "1 Acre (6 Plots)",
    "2 Acres",
    "5 Acres",
    "10 Acres",
    "Farm Land",
    "Industrial Land",
  ],

  Shop: [
    "Single Shop",
    "Double Shop",
    "Triple Shop",
    "Kiosk",
    "Open Stall",
    "Complex Unit",
    "Market Stall",
    "Plaza Shop",
    "Mall Space",
  ],

  Office: [
    "Small Office",
    "Medium Office",
    "Large Office",
    "Executive Office",
    "Corporate Floor",
    "Co-working Space",
    "Conference Hall",
    "Office Complex",
  ],

  Warehouse: [
    "Small Warehouse (1,000 sqft)",
    "Medium Warehouse (2,000 sqft)",
    "Large Warehouse (5,000 sqft)",
    "Industrial Warehouse (10,000 sqft)",
    "Distribution Center",
    "Cold Storage Facility",
  ],

  Building: [
    "Single Shop Space",
    "Retail Store",
    "Showroom",
    "Event Hall",
    "Hotel Building",
    "Hospital Building",
    "School Building",
    "Factory Space",
    "Filling Station",
  ],
};

// 🧩 Field Requirements per property type
export const propertyFieldRequirements = {
  Apartment: {
    showBedrooms: true,
    showToilets: true,
    showBathrooms: true,
    showArea: false,
    showPrice: true,
    showFeatures: true,
    showVideo: true,
    showImages: true,
    showYoutubeVideo: true,
    showDateListed: true,
  },

  Duplex: {
    showBedrooms: true,
    showToilets: true,
    showBathrooms: true,
    showArea: false,
    showPrice: true,
    showFeatures: true,
    showVideo: true,
    showImages: true,
    showYoutubeVideo: true,
    showDateListed: true,
  },

  Land: {
    showBedrooms: false,
    showToilets: false,
    showBathrooms: false,
    showArea: true,
    showPrice: true,
    showFeatures: true,
    showVideo: true,
    showImages: true,
    showYoutubeVideo: true,
    showDateListed: true,
  },

  Shop: {
    showBedrooms: false,
    showToilets: true,
    showBathrooms: false,
    showArea: true,
    showPrice: true,
    showFeatures: true,
    showVideo: true,
    showImages: true,
    showYoutubeVideo: true,
    showDateListed: true,
  },

  Office: {
    showBedrooms: false,
    showToilets: true,
    showBathrooms: true,
    showArea: true,
    showPrice: true,
    showFeatures: true,
    showVideo: true,
    showImages: true,
    showYoutubeVideo: true,
    showDateListed: true,
  },

  Warehouse: {
    showBedrooms: false,
    showToilets: true,
    showBathrooms: false,
    showArea: true,
    showPrice: true,
    showFeatures: true,
    showVideo: true,
    showImages: true,
    showYoutubeVideo: true,
    showDateListed: true,
  },

  Building: {
    showBedrooms: false,
    showToilets: true,
    showBathrooms: true,
    showArea: true,
    showPrice: true,
    showFeatures: true,
    showVideo: true,
    showImages: true,
    showYoutubeVideo: true,
    showDateListed: true,
  },
};
